apiVersion: v1
kind: Pod

metadata:
  name: overcommit-demo

spec:
  containers:
  - name: app
    image: loadtest:v1

    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"

      limits:
        cpu: "2"
        memory: "1Gi"