apiVersion: v1
kind: Pod

metadata:
  name: huge-request

spec:
  containers:
  - name: app
    image: busybox

    command:
    - sh
    - -c
    - sleep 3600

    resources:
      requests:
        cpu: "8"
        memory: "16Gi"

      limits:
        cpu: "8"
        memory: "16Gi"