apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
    project: k8s-02
spec:
  replicas: 1
  selector:           # ← SELECTOR: Which Pods to route to. # <-- "I am looking for any Pods labeled 'app: payment-api'"
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:              # ← LABELS: Matched by Service # <-- "When I spin up new Pods, I stamp them with this exact label"
        app: fastapi
        version: v1
        tier: backend
    spec:
      containers:
      - name: fastapi
        image: fastapi-demo:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: "development"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
