apiVersion: v1
kind: Pod
metadata:
  name: hello-kubernetes-labeled
  labels:
    app: hello
    environment: learning
    project: k8s-01
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
